# Numpy　数値計算

In [47]:
import numpy as np

In [48]:
x = np.array([1,2,3])

In [49]:
x

array([1, 2, 3])

In [50]:
y = np.array([2, 3.9, 6.1])

In [51]:
x.mean()

2.0

In [52]:
y.mean()

4.0

In [53]:
xc = x - x.mean()

In [54]:
yc = y - y.mean()

In [55]:
xc

array([-1.,  0.,  1.])

In [56]:
yc

array([-2. , -0.1,  2.1])

In [57]:
# パラメータaの計算

In [58]:
xx = xc ** 2

In [59]:
xx

array([1., 0., 1.])

In [60]:
xy = xc * yc

In [61]:
xy

array([ 2. , -0. ,  2.1])

In [62]:
xx.sum()

2.0

In [63]:
xy.sum()

4.1

In [64]:
a = xy.sum() / xx.sum()

In [65]:
a

2.05

# Pandas: データベースの操作

In [66]:
import pandas as pd

In [67]:
# CSVファイルの読み込み
df = pd.read_csv('sample.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'sample.csv'

In [ ]:
df

In [ ]:
# データの抽出
x = df['x']
y = df['y']

# Matplotlib グラフの描画

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# 横軸をx、縦軸をyの散布図（scatter）をプロット
plt.scatter(x,y)
plt.show()

# 単回帰分析の実装

# データの中心化

In [ ]:
# データの概要を表示
df.describe()

In [ ]:
df.mean()

In [ ]:
df_c = df - df.mean()

In [ ]:
df_c.describe()

In [ ]:
# データの抽出
x = df_c['x']
y = df_c['y']

In [ ]:
plt.scatter(x,y)
plt.show()

## パラメータaの計算

In [ ]:
xx = x * x
xy = x * y

In [ ]:
a = xy.sum() / xx.sum()

In [ ]:
a

In [ ]:
plt.scatter(x,y, label='y')  # 実測値
plt.plot(x, a*x, label='y_hat', color='red')  # 予測値
plt.legend()  # 凡例の表示
plt.show()

In [ ]:
x_new = 40  # 40平米の部屋

In [ ]:
mean = df.mean()

In [ ]:
mean['x']

In [ ]:
# 中心化
xc = x_new - mean['x']

In [ ]:
xc

In [ ]:
# 単回帰分析による予測
yc = a * xc

In [ ]:
# 元のスケールのよそ奥地
y_hat = yc + mean['y']

In [ ]:
y_hat
a

## 予測値を計算する関数の作成

In [ ]:
def predict(x):
    # 定数項
    a = 10069.022519284063
    xm = mean['x']
    ym = mean['y']
    # 中心化
    xc = x - xm
    # 予測値の計算
    y_hat = a * xc + ym
    return y_hat

In [ ]:
predict(40)

In [ ]:
predict(30)
# predict(25) 外挿の範囲

In [ ]:
print("aa")